#include "keeloq_learning_types.h"

const char* KeeloqLearningType::LearningNames[] = {
	"KEELOQ_LEARNING_SIMPLE",
	"KEELOQ_LEARNING_SIMPLE_REV",
	"KEELOQ_LEARNING_NORMAL",
	"KEELOQ_LEARNING_NORMAL_REV",
	"KEELOQ_LEARNING_SECURE",
	"KEELOQ_LEARNING_SECURE_REV",
	"KEELOQ_LEARNING_MAGIC_XOR_TYPE_1",
	"KEELOQ_LEARNING_MAGIC_XOR_TYPE_1_REV",
	"KEELOQ_LEARNING_FAAC",
	"KEELOQ_LEARNING_FAAC_REV",
	"KEELOQ_LEARNING_MAGIC_SERIAL_TYPE_1",
	"KEELOQ_LEARNING_MAGIC_SERIAL_TYPE_1_REV",
	"KEELOQ_LEARNING_MAGIC_SERIAL_TYPE_2",
	"KEELOQ_LEARNING_MAGIC_SERIAL_TYPE_2_REV",
	"KEELOQ_LEARNING_MAGIC_SERIAL_TYPE_3",
	"KEELOQ_LEARNING_MAGIC_SERIAL_TYPE_3_REV",
};

const size_t KeeloqLearningType::LearningNamesCount = sizeof(LearningNames) / sizeof(char*);