name: Linux
on:
  push:
    tags:
      - test-linux*
      - release-v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - id: actor
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.actor }}

      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          submodules: 'true'

      - name: Linux build using docker
        run: chmod +x build.sh && ./build.sh

      - name: Tag container
        run: docker tag cudakeeloq:local ghcr.io/${{ steps.actor.outputs.lowercase }}/cudakeeloq:${{ github.ref_name }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Push to ghcr.io
        run: docker push ghcr.io/${{ steps.actor.outputs.lowercase }}/cudakeeloq:${{ github.ref_name }}

